POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "ninhphan",
  "password": "ninhphan"
} 

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "ninhphan",
  "password": "ninhphan"
}

### 

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGYyODY2NWMxMjI5NzRiYjQzYWIxOGEiLCJpYXQiOjE2MjY1MDY5NzB9.NuG6I38Y8OthrfOJT-Bc9Oq993uflQIpczxwIIKRydA

{
  "title": "Fourth post",
  "description": "Bootstrap",
  "url": "https://react-bootstrap.github.io/",
  "status": "TO LEARN"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGYyODY2NWMxMjI5NzRiYjQzYWIxOGEiLCJpYXQiOjE2MjY1MDY5NzB9.NuG6I38Y8OthrfOJT-Bc9Oq993uflQIpczxwIIKRydA

###

PUT http://localhost:5000/api/posts/60f28ebd97e5dd52a47dfb49
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGYyODY2NWMxMjI5NzRiYjQzYWIxOGEiLCJpYXQiOjE2MjY1MDY5NzB9.NuG6I38Y8OthrfOJT-Bc9Oq993uflQIpczxwIIKRydA

{
  "title": "Vue",
  "description": "Vue",
  "url": "vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/60f28ebd97e5dd52a47dfb49
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGYyODY2NWMxMjI5NzRiYjQzYWIxOGEiLCJpYXQiOjE2MjY1MDY5NzB9.NuG6I38Y8OthrfOJT-Bc9Oq993uflQIpczxwIIKRydA